services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
      - MONGO_INITDB_ROOT_USERNAME=dev
    ports:
      - '27017:27017'

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
