name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test

      - name: Extract version from build.gradle
        run: |
          REMOTE_ARDUINO_DOCKER_TAG=$(grep "^version" build.gradle | awk -F= '{print $2}' | xargs)
          echo "REMOTE_ARDUINO_DOCKER_TAG=$REMOTE_ARDUINO_DOCKER_TAG" >> $GITHUB_ENV

      - name: Define Docker image
        run: |
          REMOTE_ARDUINO_DOCKER_IMAGE_FULL=${{ vars.REMOTE_ARDUINO_DOCKER_IMAGE }}:${{ env.REMOTE_ARDUINO_DOCKER_TAG }}

      - name: Build Docker image
        run: docker build -t ${{ env.REMOTE_ARDUINO_DOCKER_IMAGE_FULL }} .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ env.REMOTE_ARDUINO_DOCKER_IMAGE_FULL }}
